# Quick implementation and NB comparison

In [8]:
#imports

#data and data processing
import pandas as pd
import numpy as np

#ML data manipulation
from sklearn.datasets import make_hastie_10_2 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_validate
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold

#ML algos
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

#ML algo metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

#viz
import matplotlib.pyplot as plt
import seaborn as sns

#make the viz appear in jl
%matplotlib inline

In [9]:
#generate data and do some quick pre-processing
X, y = make_hastie_10_2(n_samples=8000, random_state=42)

y = [obs if obs==1 else 0 for obs in y]

print('class balance of y')
print()
print('1s in y: ', np.sum(y))
print('0s in y: ', len(y)-np.sum(y))

df_features = pd.DataFrame(X)
df_features.head()

class balance of y

1s in y:  4034.0
0s in y:  3966.0


0         1         2         3         4         5         6  \
0  0.496714 -0.138264  0.647689  1.523030 -0.234153 -0.234137  1.579213   
1 -0.463418 -0.465730  0.241962 -1.913280 -1.724918 -0.562288 -1.012831   
2  1.465649 -0.225776  0.067528 -1.424748 -0.544383  0.110923 -1.150994   
3 -0.601707  1.852278 -0.013497 -1.057711  0.822545 -1.220844  0.208864   
4  0.738467  0.171368 -0.115648 -0.301104 -1.478522 -0.719844 -0.460639   

          7         8         9  
0  0.767435 -0.469474  0.542560  
1  0.314247 -0.908024 -1.412304  
2  0.375698 -0.600639 -0.291694  
3 -1.959670 -1.328186  0.196861  
4  1.057122  0.343618 -1.763040

In [15]:
#train test split and scaling

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

ss = StandardScaler()
X_train_sc = ss.fit_transform(X_train)
X_test_sc = ss.transform(X_test)

nb = GaussianNB()
dt = DecisionTreeClassifier(criterion='entropy')

Ok, here we go: fit the nb and dt models below

In [21]:
#fit the nb object to the training data in the line below

#fit the dt object to the training data in the line below

Let's get the predictions on the training data each algo made

take each classifier object and use .predict() with the appropriate arguments

In [13]:
#take the nb object
#add .predict()
#and fill in .predict() with the appropraite argument

nb_train_preds =  

#take the dt object
#add .predict()
#and fill in .predict() with the appropraite argument
dt_train_preds =  

Let's fill out a confusion matrix for the training predicions

In [14]:
#create a confusion matrix here for the nb training preds
nb_train_confusion_matrix = 

#create a confusion matrix here for the dt training preds
dt_train_confustion_matrix =

print(nb_train_confusion_matrix)
print(dt_train_confustion_matrix)

[[3038   27]
 [ 131 3204]]
[[3169    0]
 [   0 3231]]


Let's do the same as above but for the test data:

get predictions, and then make a confusion matrix

so first, get predictions for the test data

In [16]:
#take the nb object
#add .predict()
#and fill in .predict() with the appropraite argument
nb_test_preds =  

#take the dt object
#add .predict()
#and fill in .predict() with the appropraite argument
dt_test_preds =  

Aaaaaand the confusion matrices for the test predictions

In [19]:
#create a confusion matrix here for the nb test preds
nb_test_confusion_matrix = 

#create a confusion matrix here for the dt test preds
dt_test_confustion_matrix = 

print(nb_test_confusion_matrix)
print(dt_test_confustion_matrix)

[[754   3]
 [ 43 800]]
[[652 188]
 [145 615]]


For each algo: 

  - compare their train and test matrices, and analyze in terms of bias and variance
  - compare the test confusion matrices against each other.  Which algo is performing better and why?